const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const state={app:"Generative Sequencer",k:[.5,.5,.5,.5],cv:[0,0,0,0],gateIn:[false,false],cvOut:[0,0],gateOut:[false,false],bpm:120,step:0,generated:null,audio:{ctx:null,osc:null,gain:null,filter:null}};
const apps={
"Generative Sequencer":{desc:"4-step probability sequencer with CV modulation and two gate outputs.",render(ctx,w,h,t){ctx.clearRect(0,0,w,h);ctx.strokeStyle="#23e0b3";ctx.lineWidth=3;const probs=[state.k[0],state.k[1],state.k[2],state.k[3]];for(let i=0;i<4;i++){const x=30+i*80,y=h-24,bar=30+probs[i]*100;ctx.fillStyle=i===state.step?"#23e0b3":"#254a53";ctx.fillRect(x,y-bar,44,bar);ctx.fillStyle="#b8e8dd";ctx.font="12px sans-serif";ctx.fillText(`${i+1}`,x+17,h-8)}},tick(){const p=Math.min(1,Math.max(0,state.k[state.step]+state.cv[0]/20));const hit=Math.random()<p;state.gateOut[0]=hit;state.gateOut[1]=state.step===0;state.cvOut[0]=(state.step-1.5)+state.k[1]*2;state.cvOut[1]=(Math.random()*2-1)*5*state.k[2];setTimeout(()=>{state.gateOut=[false,false];updateMeters()},70);state.step=(state.step+1)%4},audio(){setTone(110+state.step*55+state.cv[0]*10,.08+state.k[0]*.15)}},
"Dual LFO":{desc:"Two modulation oscillators with independent rate/shape.",render(ctx,w,h,t){ctx.clearRect(0,0,w,h);ctx.strokeStyle="#70c7ff";ctx.lineWidth=2;for(let ch=0;ch<2;ch++){ctx.beginPath();for(let x=0;x<w;x++){const f=(ch?2.2:1)*(.2+state.k[ch]*3);const y=h/2+Math.sin(x/w*Math.PI*2*f+t*(ch?2:1.3))*35*(ch?-.8:1);x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()}},tick(){const t=performance.now()/1000;state.cvOut[0]=Math.sin(t*(.3+state.k[0]*8))*5;state.cvOut[1]=Math.sin(t*(.15+state.k[1]*5)+1.2)*5;state.gateOut[0]=state.cvOut[0]>0;state.gateOut[1]=state.cvOut[1]>0},audio(){setTone(90+state.k[2]*700,.05)}},
"Quantizer":{desc:"CV quantizer with scale selection and octave shift.",render(ctx,w,h,t){ctx.clearRect(0,0,w,h);ctx.fillStyle="#23e0b3";ctx.font="bold 24px sans-serif";const notes=["C","D","E","G","A"];const n=notes[Math.abs(Math.round(state.cvOut[0]*5))%notes.length];ctx.fillText(`NOTE  ${n}`,28,65);ctx.font="14px sans-serif";ctx.fillStyle="#9abdc6";ctx.fillText(`IN ${state.cv[0].toFixed(2)}V  →  OUT ${state.cvOut[0].toFixed(3)}V`,28,105)},tick(){const semis=Math.round(state.cv[0]*12),major=[0,2,4,5,7,9,11],octave=Math.floor(semis/12),s=((semis%12)+12)%12,q=major.reduce((a,b)=>Math.abs(b-s)<Math.abs(a-s)?b:a,0);state.cvOut[0]=octave+q/12;state.cvOut[1]=state.cvOut[0]+state.k[1]*2-1;state.gateOut[0]=state.gateIn[0]},audio(){setTone(220*Math.pow(2,state.cvOut[0]),.08)}},
"Macro Oscillator":{desc:"Playable digital oscillator for testing the audio/DSP interaction.",render(ctx,w,h,t){ctx.clearRect(0,0,w,h);ctx.strokeStyle="#23e0b3";ctx.lineWidth=2;ctx.beginPath();for(let x=0;x<w;x++){const p=x/w*Math.PI*8,morph=state.k[1],y=h/2+(Math.sin(p)*(1-morph)+Math.sign(Math.sin(p))*morph)*45;x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()},tick(){state.cvOut[0]=state.cv[0];state.cvOut[1]=state.k[2]*10-5},audio(){setTone(55+state.k[0]*880+state.cv[0]*110,.12)}},
"Random Utility":{desc:"Clocked random voltages, probability gates and sample/hold.",render(ctx,w,h,t){ctx.clearRect(0,0,w,h);ctx.fillStyle="#70c7ff";ctx.font="bold 22px monospace";ctx.fillText(`R1 ${state.cvOut[0].toFixed(2)}V`,35,60);ctx.fillText(`R2 ${state.cvOut[1].toFixed(2)}V`,35,105)},tick(){state.cvOut[0]=(Math.random()*2-1)*5;state.cvOut[1]=(Math.random()*2-1)*5;state.gateOut[0]=Math.random()<state.k[0];state.gateOut[1]=Math.random()<state.k[1];setTimeout(()=>{state.gateOut=[false,false];updateMeters()},100)},audio(){setTone(80+Math.random()*1000,.04)}},
"Stereo Delay":{desc:"UI/audio proof-of-concept for an effect-style MOKU app.",render(ctx,w,h,t){ctx.clearRect(0,0,w,h);ctx.fillStyle="#23e0b3";ctx.font="bold 18px sans-serif";ctx.fillText(`TIME ${(50+state.k[0]*950).toFixed(0)} ms`,30,50);ctx.fillText(`FEEDBACK ${(state.k[1]*95).toFixed(0)} %`,30,85);ctx.fillText(`MIX ${(state.k[2]*100).toFixed(0)} %`,30,120)},tick(){state.cvOut[0]=state.k[0]*10-5;state.cvOut[1]=state.k[1]*10-5},audio(){setTone(140+state.k[3]*500,.06)}}};
const storeApps=Object.entries(apps).map(([name,a],i)=>({name,desc:a.desc,price:i<3?"Free":`$${[4.99,6.99,8.99][(i-3)%3]}`}));
function setTone(freq,gain=.08){const a=state.audio;if(!a.ctx||!a.osc)return;a.osc.frequency.setTargetAtTime(Math.max(30,Math.min(4000,freq)),a.ctx.currentTime,.01);a.gain.gain.setTargetAtTime(gain,a.ctx.currentTime,.02);if(a.filter)a.filter.frequency.setTargetAtTime(200+state.k[1]*7000,a.ctx.currentTime,.03)}
function startAudio(){if(state.audio.ctx)return;const ctx=new(window.AudioContext||window.webkitAudioContext)(),osc=ctx.createOscillator(),gain=ctx.createGain(),filter=ctx.createBiquadFilter();osc.type="sawtooth";gain.gain.value=.06;filter.type="lowpass";filter.frequency.value=1200;osc.connect(filter).connect(gain).connect(ctx.destination);osc.start();state.audio={ctx,osc,gain,filter};$("#audioState").textContent="Audio engine running."}
function stopAudio(){if(state.audio.ctx){state.audio.ctx.close();state.audio={ctx:null,osc:null,gain:null,filter:null}}$("#audioState").textContent="Audio engine off."}
function populate(){const sel=$("#appSelect");Object.keys(apps).forEach(n=>{const o=document.createElement("option");o.textContent=n;sel.appendChild(o)});$("#storeGrid").innerHTML=storeApps.map(a=>`<div class="app-card"><h3>${a.name}</h3><p>${a.desc}</p><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px"><strong>${a.price}</strong><span style="font-size:10px;color:#6f8d97">MOKU Certified</span></div><button data-install="${a.name}">Install</button></div>`).join("")}
function loadApp(name){state.app=name;$("#appSelect").value=name;$("#screenTitle").textContent=name.toUpperCase();$("#screenStatus").textContent=apps[name]?.desc||"Generated MOKU app";apps[name]?.audio?.()}
function updateMeters(){$("#cvo1v").textContent=`${state.cvOut[0].toFixed(2)}V`;$("#cvo2v").textContent=`${state.cvOut[1].toFixed(2)}V`;$("#gout1v").textContent=state.gateOut[0]?"HIGH":"LOW";$("#gout2v").textContent=state.gateOut[1]?"HIGH":"LOW";document.querySelector('[data-jack="gout1"]').classList.toggle("hot",state.gateOut[0]);document.querySelector('[data-jack="gout2"]').classList.toggle("hot",state.gateOut[1])}
function bind(){[1,2,3,4].forEach(i=>$("#k"+i).addEventListener("input",e=>{state.k[i-1]=e.target.value/100;$("#k"+i+"v").textContent=e.target.value;apps[state.app]?.audio?.()}));$("#cv1src").addEventListener("input",e=>{state.cv[0]=e.target.value/10;$("#cv1v").textContent=state.cv[0].toFixed(2)+"V"});$("#cv2src").addEventListener("input",e=>{state.cv[1]=e.target.value/10;$("#cv2v").textContent=state.cv[1].toFixed(2)+"V"});$("#bpm").addEventListener("input",e=>{state.bpm=+e.target.value;$("#bpmv").textContent=e.target.value});$("#gate1").addEventListener("pointerdown",()=>state.gateIn[0]=true);$("#gate1").addEventListener("pointerup",()=>state.gateIn[0]=false);$("#gate2").addEventListener("pointerdown",()=>state.gateIn[1]=true);$("#gate2").addEventListener("pointerup",()=>state.gateIn[1]=false);$("#appSelect").addEventListener("change",e=>loadApp(e.target.value));$("#audioStart").onclick=startAudio;$("#audioStop").onclick=stopAudio;$("#panicBtn").onclick=()=>{state.gateOut=[false,false];state.gateIn=[false,false];updateMeters();stopAudio()};$("#saveBtn").onclick=()=>localStorage.setItem("mokuPatch",JSON.stringify({app:state.app,k:state.k,cv:state.cv,bpm:state.bpm}));$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tab-'+b.dataset.tab).classList.add('active')});$("#storeGrid").addEventListener("click",e=>{if(e.target.dataset.install){loadApp(e.target.dataset.install);e.target.textContent="Installed ✓"}});$("#generateBtn").onclick=generateMock;$("#loadGeneratedBtn").onclick=()=>{if(state.generated){$("#screenTitle").textContent=state.generated.name.toUpperCase();$("#screenStatus").textContent=state.generated.summary}};$$('[data-btn]').forEach(b=>b.onclick=()=>{if(b.dataset.btn==='random'){[1,2,3,4].forEach(i=>{$('#k'+i).value=Math.round(Math.random()*100);$('#k'+i).dispatchEvent(new Event('input'))})}})}
function generateMock(){const p=$("#aiPrompt").value.toLowerCase();let type=p.includes("lfo")?"Dual LFO":p.includes("quant")?"Quantizer":p.includes("osc")?"Macro Oscillator":p.includes("delay")?"Stereo Delay":p.includes("random")?"Random Utility":"Generative Sequencer";const mapping={name:"AI "+type,base:type,summary:`Generated from prompt using safe MOKU mappings. Base engine: ${type}.`,io:{cv1:p.includes("cv1")?"modulation":"optional",gate1:p.includes("gate")?"rhythm/trigger":"optional",k1:p.includes("probab")?"probability":"primary parameter",k2:p.includes("transpose")?"transpose":"secondary parameter"}};state.generated=mapping;$("#aiResult").textContent=JSON.stringify(mapping,null,2);$("#loadGeneratedBtn").disabled=false}
const canvas=$("#screenCanvas"),ctx=canvas.getContext("2d");let lastStep=0;function loop(t){const app=apps[state.app]||apps["Generative Sequencer"];if(t-lastStep>60000/state.bpm){app.tick?.();app.audio?.();lastStep=t;updateMeters()}app.render?.(ctx,canvas.width,canvas.height,t/1000);requestAnimationFrame(loop)}
populate();bind();const saved=localStorage.getItem("mokuPatch");if(saved){try{const s=JSON.parse(saved);state.k=s.k||state.k;state.bpm=s.bpm||120;[1,2,3,4].forEach(i=>{$("#k"+i).value=state.k[i-1]*100;$("#k"+i+"v").textContent=Math.round(state.k[i-1]*100)});$("#bpm").value=state.bpm;$("#bpmv").textContent=state.bpm;loadApp(s.app||state.app)}catch{}}loadApp(state.app);requestAnimationFrame(loop);
