const $=s=>document.querySelector(s);
const state={bpm:120,running:true,step:0,last:0,cv:[0,0],gateIn:[false,false],rows:[{cv:[.2,.65,.4,.78,.52,.9,.3,.7],gate:[1,1,0,1,1,0,1,1]},{cv:[.7,.35,.82,.18,.55,.72,.28,.9],gate:[1,0,1,1,1,0,1,1]}]};
const grid=$('#seqGrid');
function buildGrid(){grid.innerHTML='';['A','B'].forEach((name,r)=>{let lab=document.createElement('div');lab.className='row-label';lab.textContent='CV '+name;grid.append(lab);for(let i=0;i<8;i++){let c=document.createElement('div');c.className='step-cell '+(r?'rowb':'');c.dataset.r=r;c.dataset.i=i;c.innerHTML='<div class="step-bar"></div>';grid.append(c)}let gl=document.createElement('div');gl.className='row-label';gl.textContent='GATE '+name;grid.append(gl);for(let i=0;i<8;i++){let g=document.createElement('button');g.className='gate-cell '+(r?'rowb ':'')+(state.rows[r].gate[i]?'on':'');g.dataset.r=r;g.dataset.i=i;grid.append(g)}let blank=document.createElement('div');blank.className='row-label';grid.append(blank);for(let i=0;i<8;i++){let n=document.createElement('div');n.className='step-num';n.textContent=i+1;grid.append(n)}});bindSteps();renderSeq()}
function bindSteps(){document.querySelectorAll('.step-cell').forEach(c=>{let startY,startV;const move=e=>{if(startY==null)return;let y=e.clientY;let v=Math.max(0,Math.min(1,startV+(startY-y)/90));state.rows[+c.dataset.r].cv[+c.dataset.i]=v;renderSeq()};c.onpointerdown=e=>{startY=e.clientY;startV=state.rows[+c.dataset.r].cv[+c.dataset.i];c.setPointerCapture?.(e.pointerId)};c.onpointermove=move;c.onpointerup=c.onpointercancel=()=>startY=null});document.querySelectorAll('.gate-cell').forEach(g=>g.onclick=()=>{let r=+g.dataset.r,i=+g.dataset.i;state.rows[r].gate[i]=state.rows[r].gate[i]?0:1;renderSeq()})}
function volts(v){return (v*10-5).toFixed(2)+'V'}
function renderSeq(){document.querySelectorAll('.step-cell').forEach(c=>{let r=+c.dataset.r,i=+c.dataset.i,v=state.rows[r].cv[i];c.querySelector('.step-bar').style.height=(v*100)+'%';c.classList.toggle('current',state.running&&i===state.step)});document.querySelectorAll('.gate-cell').forEach(g=>g.classList.toggle('on',!!state.rows[+g.dataset.r].gate[+g.dataset.i]));$('#stepRead').textContent=(state.step+1)+' / 8';let a=state.rows[0],b=state.rows[1];$('#outCv1').textContent=volts(a.cv[state.step]);$('#outCv2').textContent=volts(b.cv[state.step]);$('#monCv1').textContent=volts(a.cv[state.step]);$('#monCv2').textContent=volts(b.cv[state.step]);let ga=state.running&&!!a.gate[state.step],gb=state.running&&!!b.gate[state.step];$('#gateOut1').textContent=ga?'HIGH':'LOW';$('#gateOut2').textContent=gb?'HIGH':'LOW';$('#monGate1').textContent=ga?'HIGH':'LOW';$('#monGate2').textContent=gb?'HIGH':'LOW';$('#gateJack1').classList.toggle('hot',ga);$('#gateJack2').classList.toggle('hot',gb)}
function setBpm(v){state.bpm=Math.max(30,Math.min(240,Math.round(v)));$('#bpm').value=state.bpm;$('#bpmVal').textContent=state.bpm;$('#screenBpm').textContent=state.bpm.toFixed(1)}
$('#bpm').oninput=e=>setBpm(+e.target.value);$('#halfBtn').onclick=()=>setBpm(state.bpm/2);$('#doubleBtn').onclick=()=>setBpm(state.bpm*2);let taps=[];$('#tapBtn').onclick=()=>{let n=performance.now();taps.push(n);taps=taps.slice(-4);if(taps.length>1){let avg=(taps[taps.length-1]-taps[0])/(taps.length-1);setBpm(60000/avg)}};
function setCV(i,v){state.cv[i]=v;$('#cv'+(i+1)+'Val').textContent=v.toFixed(2)+'V';$('#inCv'+(i+1)).textContent=v.toFixed(2)+'V'}$('#cv1').oninput=e=>setCV(0,+e.target.value/100);$('#cv2').oninput=e=>setCV(1,+e.target.value/100);
function toggleRun(){state.running=!state.running;$('#runBtn').textContent=state.running?'■':'▶';$('#runText').textContent=state.running?'RUN':'STOP';$('#runLed').style.color=state.running?'var(--green)':'#52656b';renderSeq()}$('#runBtn').onclick=toggleRun;
function gateButton(i,down){state.gateIn[i]=down;let b=$('#gate'+(i+1)+'Btn');b.classList.toggle('active',down);b.textContent='Gate '+(i+1)+(down?' · HIGH':'');if(i===0)$('#gateInRead').textContent=down?'HIGH':'LOW'};[1,2].forEach(n=>{let b=$('#gate'+n+'Btn');b.onpointerdown=()=>gateButton(n-1,true);b.onpointerup=b.onpointercancel=()=>gateButton(n-1,false)});
$('#resetBtn').onclick=()=>{state.rows[0].cv=[.2,.65,.4,.78,.52,.9,.3,.7];state.rows[0].gate=[1,1,0,1,1,0,1,1];state.rows[1].cv=[.7,.35,.82,.18,.55,.72,.28,.9];state.rows[1].gate=[1,0,1,1,1,0,1,1];state.step=0;setBpm(120);setCV(0,0);setCV(1,0);$('#cv1').value=0;$('#cv2').value=0;renderSeq()};
function loop(t){if(state.running&&t-state.last>=60000/state.bpm){state.last=t;state.step=(state.step+1)%8;renderSeq()}requestAnimationFrame(loop)}
buildGrid();setBpm(120);setCV(0,0);setCV(1,0);requestAnimationFrame(loop);